name: hoge hoge

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        export VERSION=$(echo $GITHUB_REF | sed "s#refs/tags/##")
    - name: hoge
      run: |
         echo ${VERSION}
