name: hoge hoge

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      id: tag
      run: |
        echo $GITHUB_REF | sed "s#refs/tags/##"
    - name: hoge
      run: |
         echo ${{ steps.tag.outputs.stdout }}
